/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

// #define AUTO_SHIFT_TIMEOUT 170
// #define NO_AUTO_SHIFT_SPECIAL
// #define NO_AUTO_SHIFT_NUMERIC
// #define RETRO_SHIFT 500

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY

#define QUICK_TAP_TERM 200
#define QUICK_TAP_TERM_PER_KEY

#define PERMISSIVE_HOLD true
#define PERMISSIVE_HOLD_PER_KEY

#define HOLD_ON_OTHER_KEY_PRESS false
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define TAPPING_FORCE_HOLD true
#define TAPPING_FORCE_HOLD_PER_KEY
